### ISSUE TITLE
Bad filename

### ISSUE THREAD

**Issue by popov1024** [streamdp/phonebook#1]
Bad filename in the repository:
- https://github.com/streamdp/phonebook/blob/main/static/img/strukturnoe_podrazdelenye_1/bukhhalteryia/sektor_raschetov_s_personalom/ObjectID(%22604c3dcf0e558a1f46742dc3%22).jpg

**Comment by streamdp** [comment]
You are correct, I should have deleted the test data.
i'm fixed this and re-run container.

ср, 17 мар. 2021 г. в 10:26, Andrey Popov ***@***.***>:
